
; CDF tsmc13lg/vpnphv5 generated by GTE Version: v2.7alpha  Build: 121203_09:07 on Dec 15, 2003

LIBRARY="tsmc13lg"
CELL="vpnphv5"

let((cellId cdfId)
    unless(cellId=ddGetObj(LIBRARY CELL)
        error("Could not get cell %s." CELL)
    )
    when(cdfId=cdfGetBaseCellCDF(cellId)
        cdfDeleteCDF(cdfId)
    )
    cdfId=cdfCreateBaseCellCDF(cellId)


    cdfId->simInfo = list(nil)

    cdfSaveCDF(cdfId)
)
